MomAndBaby/Pages/Dashboard/Body/AccountDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MomAndBaby.BusinessObject.Entity;
using MomAndBaby.BusinessObject.Enums;
using MomAndBaby.Service;
using MomAndBaby.Service.OrderService;
using MomAndBaby.Utilities.Constants;

namespace MomAndBaby.Pages.Dashboard.Body
{
    public class AccountDetailModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly IOrderService _orderService;

        public AccountDetailModel(IUserService userService, IOrderService orderService)
        {
            _userService = userService;
            _orderService = orderService;
        }

        public User User { get; set; }
        public int NumOfOrders {get; set; }
        public decimal TotalAmount { get; set; }
        public IEnumerable<string> ShippingAddress { get; set; }
        public async Task<IActionResult> OnGet(Guid? id)
        {
            ViewData[VariableConstant.CurrentMenu] = (int)Menu.AccountDetail;
            if (id == null)
            {
                ViewData["Message"] = "Id not found";
                return Page();
            }
            var user = await _userService.GetUserById(id);

            if (user == null)
            {
                ViewData["Message"] = "User not found";
                return Page();
            }

            var listAddress = await _orderService.GetShippingAddress(user.Id);
            var orders = await _orderService.GetAllOrder(user.Id);
            
            User = user;
            ShippingAddress = listAddress!;
            NumOfOrders = orders.Count();
            TotalAmount = await _orderService.GetTotalAmount(user.Id);
            return Page();
        }

        public async Task<IActionResult> OnPostBanAccount(Guid userId)
        {
            var user = await _userService.GetUserById(userId);
            user.Status = UserStatus.Banned.ToString();
            await _userService.UpdateUser(user);
           
            return await OnGet(userId);
        }
    }
}

MomAndBaby/Pages/Dashboard/Body/AddArticle.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MomAndBaby.BusinessObject.Constants;
using MomAndBaby.BusinessObject.Entity;
using MomAndBaby.BusinessObject.Enums;
using MomAndBaby.BusinessObject.Models;
using MomAndBaby.Repository;
using MomAndBaby.Service;
using MomAndBaby.Service.Extension;
using MomAndBaby.Service.Service.Cloudinary;
using MomAndBaby.Service.Worker;
using MomAndBaby.Utilities.Constants;

namespace MomAndBaby.Pages.Dashboard.Body
{
	public class AddArticleModel : PageModel
	{
		private readonly IArticleService _articleService;
		private readonly NotificationWorker _notificationWorker;
		private readonly ICloudinaryService _cloudinaryService;

		public AddArticleModel(IArticleService articleService, NotificationWorker notificationWorker, ICloudinaryService cloudinaryService)
		{
			_articleService = articleService;
			_notificationWorker = notificationWorker;
			_cloudinaryService = cloudinaryService;
		}

		[BindProperty]
		public ArticleDTO ArticleDTO { get; set; }
		public IActionResult OnGet()
		{
			ViewData[VariableConstant.CurrentMenu] = (int)Menu.PostAdd;
			//var userRole = User.Claims.FirstOrDefault(u => u.Type.Equals(UserClaimType.Role)).Value.ToString().ToLower();
   //         if (userRole != "2" || userRole != "1")
			//{
			//	return Redirect("/article");
			//}
			return Page();
		}

		public async Task<IActionResult> OnPostAsync(IFormFile ImageUpload)
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			var image = await _cloudinaryService.UploadAsync(ImageUpload);

			Article articleToCreate = new Article
			{
				AuthorId = Guid.Parse(User.Claims.FirstOrDefault(u => u.Type.Equals(UserClaimType.UserId))?.Value.ToString()),
				Title = ArticleDTO.Title,
				Content = ArticleDTO.Content,
				CreatedAt = DateTime.Now,
				Image = image.Url.ToString(),
				Status = true
			};

			await _articleService.AddArticle(articleToCreate);
			//var articleJustCreated = await _articleService.GetNewestArticle();
			//int newArticleId = articleJustCreated.Id;

			//if (ImageUpload != null && ImageUpload.Length > 0)
			//{
			//	var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/article-image", $"{newArticleId}.jpg");

			//	using (var stream = new FileStream(filePath, FileMode.Create))
			//	{
			//		await ImageUpload.CopyToAsync(stream);
			//	}
			//}

			return Redirect("/article");
		}
	}
}

MomAndBaby/Pages/Dashboard/Body/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MomAndBaby.BusinessObject.Constants;
using MomAndBaby.BusinessObject.Entity;
using MomAndBaby.BusinessObject.Enums;
using MomAndBaby.BusinessObject.Models;
using MomAndBaby.Middleware;
using MomAndBaby.Service;
using MomAndBaby.Service.Extension;
using MomAndBaby.Service.OrderService;
using MomAndBaby.Service.Service;
using MomAndBaby.Service.Worker;
using MomAndBaby.Utilities.Constants;

namespace MomAndBaby.Pages.Dashboard.Body
{
    public class DashboardModel : PageModel
    {
        private readonly IVoucherService _voucherService;
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        private readonly IArticleService _articleService;
        private readonly IUserService _userService;
        private readonly NotificationWorker _notificationWorker;

        [BindProperty]
        public DashboardDTO DashboardDTO { get; set; } = new DashboardDTO();

        public int TotalUser { get; private set; } = 0;
        public int TotalProduct { get; private set; } = 0;
        public int TotalArticle { get; private set; } = 0;
        public int TotalOrder { get; private set; } = 0;

        public DashboardModel(IVoucherService voucherService, IProductService productService, IOrderService orderService,
            NotificationWorker notificationWorker, IArticleService articleService, IUserService userService)
        {
            _voucherService = voucherService;
            _productService = productService;
            _orderService = orderService;
            _notificationWorker = notificationWorker;
            _articleService = articleService;
            _userService = userService;
        }

        public async Task OnGet()
        {
            ViewData[VariableConstant.CurrentMenu] = (int)Menu.Dashboard;

            DashboardDTO.Vouchers = await _voucherService.GetVouchers();
            DashboardDTO.Gifts = await _voucherService.GetGifts();
            DashboardDTO.StatisticCategory = await _productService.GetStatisticsProductCategory();
            DashboardDTO.TotalMoneys = await _orderService.GetTotalAmount();

            TotalProduct = await _productService.GetTotalProduct();
            TotalArticle = await _articleService.GetTotalArticle();
            TotalOrder = await _orderService.GetTotalOrder();
            TotalUser = await _userService.GetTotalUser();
        }

        public async Task<IActionResult> OnPostDeleteVoucher(int id)
        {
            var result = await _voucherService.DeleteVoucher(id);
            _notificationWorker.DoWork(Guid.Parse(User.GetUserIdFromToken()), TableName.Voucher, NotificationType.Deleted);

            return Redirect("/dashboard");

        }
    }
}

MomAndBaby/Pages/Dashboard/Body/EditArticle.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MomAndBaby.BusinessObject.Constants;
using MomAndBaby.BusinessObject.Entity;
using MomAndBaby.BusinessObject.Enums;
using MomAndBaby.Service;
using MomAndBaby.Service.Service.Cloudinary;
using MomAndBaby.Utilities.Constants;

namespace MomAndBaby.Pages.Dashboard.Body
{
    public class EditArticleModel : PageModel
    {
        private readonly IArticleService _articleService;
        private readonly ICloudinaryService _cloudinaryService;

        public EditArticleModel(IArticleService articleService, ICloudinaryService cloudinaryService)
        {
            _articleService = articleService;
            _cloudinaryService = cloudinaryService;
        }

        [BindProperty]
        public Article Article { get; set; }

        public async Task<IActionResult> OnGet(int articleId)
        {
            Article = await _articleService.GetArticleById(articleId);
            //var userRole = User.Claims.FirstOrDefault(u => u.Type.Equals(UserClaimType.Role)).Value.ToString().ToLower();
            //if (userRole != "2" || userRole != "1")
            //{
            //    return Redirect("/article");
            //}
            ViewData[VariableConstant.CurrentMenu] = (int)Menu.PostAdd;
            if (Article == null)
            {
                return RedirectToPage("/article");
            }
            return Page();
        }

        public async Task<IActionResult> OnPost(int articleId, IFormFile ImageUpload)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var articleToUpdate = await _articleService.GetArticleById(articleId);
            if (articleToUpdate == null)
            {
                return RedirectToPage("/article");
            }

            var image = await _cloudinaryService.UploadAsync(ImageUpload);

            articleToUpdate.Title = Article.Title;
            articleToUpdate.Content = Article.Content;
            articleToUpdate.Image = image.Url.ToString();

            await _articleService.UpdateArticle(articleToUpdate, articleId);
            return Redirect("/article-detail?articleId=" + articleId);
        }

    }
}

MomAndBaby/Pages/Dashboard/Body/ListAccount.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MomAndBaby.BusinessObject.Constants;
using MomAndBaby.BusinessObject.Entity;
using MomAndBaby.BusinessObject.Enums;
using MomAndBaby.Service;
using MomAndBaby.Service.Extension;
using MomAndBaby.Service.MessageConstant;
using MomAndBaby.Service.Worker;
using MomAndBaby.Utilities.Constants;
using System.Text;

namespace MomAndBaby.Pages.Dashboard.Body
{
    public class ListAccountModel : PageModel
    {
        private readonly IUserService _userService;
        private readonly NotificationWorker _notificationWorker;

        public ListAccountModel(IUserService userService, NotificationWorker notificationWorker)
        {
            _userService = userService;
            _notificationWorker = notificationWorker;
        }


       
        public IEnumerable<User?> Users { get; set; }
       
        public int TotalPages { get; set; }
        public int CurrentPage { get; set; }
        public int? SelectedRole { get; set; }

        [BindProperty]
        public string? EmailStaff { get; set; }

        public async Task OnGet(int? pageIndex, int? role)
        {
            int pageSize = 15;
            CurrentPage = pageIndex ?? 1;
            SelectedRole = role;

            IEnumerable<User?> list;
            if (role == null)
            {
                list = await _userService.GetUsersExceptAdmin();
            }
            else
            {
                list = await _userService.GetUserByRoleId(role);
            }

            int count = list.Count();
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);
            Users = list.Skip((CurrentPage - 1) * pageSize).Take(pageSize).ToList();
            ViewData[VariableConstant.CurrentMenu] = (int)Menu.AccountList;
           
        }

        public async Task<IActionResult> OnPostUpdateStatus(string userEmail, int i, int? role)
        {
            var user = await _userService.GetUserByEmail(userEmail);
            if (user != null && user.RoleId != (int)RoleType.Admin)
            {
                await _userService.UpdateStatus(user);
                _notificationWorker.DoWork(Guid.Parse(User.GetUserIdFromToken()), TableName.Account, NotificationType.Modified);
            }
            return RedirectToPage(new { pageIndex = i, role = role });
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var users = await _userService.GetUsersExceptAdmin();
            var csv = new StringBuilder();
            csv.AppendLine("Id,UserName,FullName,Email, PhoneNumber,Address,Role,CreatedAt,UpdatedAt,Status");
            foreach (var user in users)
            {
                csv.AppendLine($"{user.Id},{user.Username},{user.FullName},{user.Email},{user.PhoneNumber},{user.Address},{user.Role.Name},{user.CreatedAt},{user.UpdatedAt},{user.Status}");
            }

            // Return the CSV file
            var byteArray = Encoding.ASCII.GetBytes(csv.ToString());
            var stream = new MemoryStream(byteArray);

            return File(stream, "text/csv", "UserList.csv");
        }

        public async Task<IActionResult> OnPostApply(int? role)
        {
            SelectedRole = role;
            return RedirectToPage(new { pageIndex = 1, role = SelectedRole });
        }

        public async Task<IActionResult> OnPostAddStaff()
        {
            var result = await _userService.AddStaff(EmailStaff);
            Users = await _userService.GetUsersExceptAdmin();
            if (result == null)
            {
                TempData["MessageRegister"] = MessageAuthen.ExistedEmail;
                
                return Page();
            }
            else
            {
                TempData["MessageRegister"] = MessageAuthen.AddStaffTrue;
                
                return Page();
            }
        }



        

        

    }
}

MomAndBaby/Pages/Dashboard/Body/ListOrder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MomAndBaby.BusinessObject.Entity;
using MomAndBaby.BusinessObject.Enums;
using MomAndBaby.BusinessObject.Models;
using MomAndBaby.Service.OrderService;
using MomAndBaby.Utilities.Constants;

namespace MomAndBaby.Pages.Dashboard.Body
{
    public class ListOrderModel : PageModel
    {
        private readonly IOrderService _orderService;
        public ListOrderModel(IOrderService orderService)
        {
            _orderService = orderService;
        }
        public IEnumerable<MomAndBaby.BusinessObject.Models.OrderResponseModel> Orders { get; set; } = new List<MomAndBaby.BusinessObject.Models.OrderResponseModel>();

        public async Task OnGet()
        {
            ViewData[VariableConstant.CurrentMenu] = (int)Menu.OrderList;
            Orders = await _orderService.GetAllOrderAdmin();
        }
    }
}

MomAndBaby/Pages/Dashboard/Body/Test.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MomAndBaby.Pages.Dashboard.Body
{
    public class TestModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MomAndBaby/Pages/Main/Authorize/SignupPage.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MomAndBaby.BusinessObject.Constants;
using MomAndBaby.BusinessObject.Entity;
using MomAndBaby.BusinessObject.Models;
using MomAndBaby.Service;
using MomAndBaby.Service.MessageConstant;
using MomAndBaby.Utilities.Helper;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Newtonsoft.Json;

namespace MomAndBaby.Pages.Main.Authorize
{
    public class SignupPageModel : PageModel
    {
        private readonly IUserService _userService;
        public SignupPageModel(IUserService userService)
        {
            _userService = userService;
        }

        [BindProperty]
        [Required(ErrorMessage = "User Name is required")]
        [RegularExpression(@"^\S*$", ErrorMessage = "User Name cannot contain spaces")]
        public string UserName { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[A-Z])(?=.*[!@#$&*]).{8,}$", ErrorMessage = "Password must be at least 8 characters long, contain at least one uppercase letter and one special character.")]
        public string Password { get; set; }


        




        public IActionResult OnGet()
        {
            if (HttpContext.Session.IsAuthenticated())
            {
                return Redirect("/");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostRegisterAccount()
        {
            if (!ModelState.IsValid)
            {
                // If the model state is not valid, return the page to display validation errors
                return Page();
            }

            var loginUserDto = new LoginUserDto(UserName, Email, Password);

            var result = await _userService.AddNewUser(loginUserDto);
            if (result == null)
            {
                TempData["MessageRegister"] = MessageAuthen.ExistedEmail;
                return Page();
            }
            TempData["Email"] = result.Email;
            HttpContext.Session.SetString("Email", Email);
            TempData["Authen"] = JsonConvert.SerializeObject(result);

            return Redirect("/verify");
        }
    }
}

MomAndBaby/Pages/Main/Body/Contact.cshtml
@page "/contact"
@model MomAndBaby.Pages.Main.Body.ContactModel
@{
    ViewData["Title"] = "Contact Us";
}

<!--== Start Page Title Area ==-->
<section class="page-title-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12 m-auto">
                <div class="page-title-content text-center">
                    <h2 class="title">Contact Us</h2>
                    <div class="bread-crumbs"><a href="index.html"> Home </a><span class="breadcrumb-sep"> // </span><span class="active"> Contact Us</span></div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--== End Page Title Area ==-->
<!--== Start Contact Area ==-->
<section class="contact-area">
    <div class="container">
        <div class="contact-page-wrap">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="contact-info-items text-center">
                        <div class="row row-gutter-80">
                            <div class="col-sm-6 col-md-4">
                                <div class="contact-info-item">
                                    <div class="icon">
                                        <img class="icon-img" src="~/main/assets/img/icons/5.png" alt="Icon">
                                    </div>
                                    <h2>Address</h2>
                                    <div class="content">
                                        <p>Ho Chi Minh City</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="contact-info-item mt-xs-30">
                                    <div class="icon">
                                        <img class="icon-img" src="~/main/assets/img/icons/6.png" alt="Icon">
                                    </div>
                                    <h2>Phone No</h2>
                                    <div class="content">
                                        <a href="tel://+00123456789">+ 00 123 456 789</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="contact-info-item mt-sm-30">
                                    <div class="icon">
                                        <img class="icon-img" src="~/main/assets/img/icons/7.png" alt="Icon">
                                    </div>
                                    <h2>Email / Web</h2>
                                    <div class="content">
                                        <a href="mailto://demo@example.com">demo@example.com</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact-map-area">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.1639869551436!2d106.79814847412324!3d10.87512905736725!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174d8a6b19d6763%3A0x143c54525028b2e!2sVNUHCM%20Student%20Cultural%20House!5e0!3m2!1sen!2ssg!4v1721558134648!5m2!1sen!2ssg" allowfullscreen="" loading="lazy"></iframe>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="contact-form">
                        <form class="contact-form-wrapper" id="contact-form" action="https://whizthemes.com/mail-php/raju/arden/mail.php" method="post">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="section-title">
                                        <h2 class="title">Send A Quest</h2>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input class="form-control" type="text" name="con_name" placeholder="Name *">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input class="form-control" type="email" name="con_email" placeholder="Email *">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <input class="form-control" type="text" placeholder="Subject (Optinal)">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <textarea class="form-control" name="con_message" placeholder="Message"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group text-center">
                                                <button class="btn btn-theme" type="submit">Send Message</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- Message Notification -->
                    <div class="form-message"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--== End Contact Area ==-->

MomAndBaby/Pages/Main/Body/GoogleResponse.cshtml
@page "/gg"
@model MomAndBaby.Pages.Main.Body.GoogleResponseModel
@{
}

MomAndBaby/Pages/Main/Body/OrderCancel.cshtml
@page "/payment-canceled"

@{
    ViewData["Title"] = "PaymentCancel";
}

    <main class="main-content">

    <!--== Start Cart Area Wrapper ==-->
    <section class="page-not-found-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 m-auto">
            <div class="error-content text-center">
              <h1>We Are Sorry, Payment has been canceled</h1>
              <p>Unfortunately your payment have some issue, we cant comfirm that your payment success. Please try pay again. <a href="/">Back to Homepage</a> </p>
              
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Cart Area Wrapper ==-->
  </main>

MomAndBaby/Pages/Main/Body/OrderConfirm.cshtml
@page "/payment-success"

@{
    ViewData["Title"] = "PaymentSuccess";
}

MomAndBaby/Pages/Main/Body/SignupPage.cshtml
@page "/register"
@using MomAndBaby.Pages.Main.Body
@model SignupPageModel

<main class="main-content">
<!--== Start Page Title Area ==-->
<section class="page-title-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12 m-auto">
                <div class="page-title-content text-center">
                    <h2 class="title">My Account</h2>
                    <div class="bread-crumbs"><a href="index.html"> Home </a><span class="breadcrumb-sep"> // </span><span class="active"> My Account</span></div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--== End Page Title Area ==-->
    <section class="login-register-area">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="login-register-content">
                    <div class="login-register-title mb-30">
                        <h2>Register</h2>
                        <p>Create new account today to reap the benefits of a personalized shopping experience. </p>
                    </div>
                    <div class="login-register-style">
                        <form method="post">
                            <div class="login-register-input">
                                
                                <input type="text" name="username" asp-for="UserName" placeholder="Username">
                                <span asp-validation-for="UserName" class="text-danger"></span>
                            </div>
                            <div class="login-register-input">
                                
                                <input type="text" name="email" asp-for="Email" placeholder="Email">
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="login-register-input">
                                
                                <input type="password" name="password" asp-for="Password" placeholder="Password">
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <div class="login-register-paragraph">
                                <p>Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our <a href="#">privacy policy.</a></p>
                            </div>
                            <div class="btn-style-3">
                                <button class="btn" asp-page-handler="RegisterAccount">Register</button>
                            </div>

                        </form>
                        <div class="text-info">@TempData["MessageRegister"]</div>
                    </div>
                </div>
            </div>
            
        </div>
</section>
        

    
    <!--== End Login Wrapper ==-->
</main>

MomAndBaby/Pages/Main/Body/VerifyAccount.cshtml
@page "/verify"
@model MomAndBaby.Pages.Main.Body.VerifyAccountModel
@{
}



<main class="main-content">
    <!--== Start Page Title Area ==-->
    <section class="page-title-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 m-auto">
                    <div class="page-title-content text-center">
                        <h2 class="title">My Account</h2>
                        <div class="bread-crumbs"><a href="index.html"> Home </a><span class="breadcrumb-sep"> // </span><span class="active"> My Account</span></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--== End Page Title Area ==-->
    <section class="login-register-area">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="login-register-content">
                    <div class="login-register-title mb-30">
                        <h2>Verify Account</h2>
                        <p style="margin-left: 60px">Please input OTP was sent in your email</p>
                    </div>
                    <div class="login-register-style">
                        <form method="post">
                            <div style="color: red; margin-bottom: 30px">@TempData["MessageVerify"]</div>
                            <div style="color: deepskyblue; margin-bottom: 30px">@TempData["MessageResend"]</div>
                           @*  <div class="login-register-input">
                                <input type="hidden" asp-for="Email" placeholder="Email" value="@Model.Email">
                            </div> *@
                            <div class="login-register-input">
                                <input type="text" asp-for="Otp" placeholder="OTP">
                            </div>
                            <button type="submit" style="color: deepskyblue; text-decoration: underline; border: none; background: none; padding: 0; margin: 0;" asp-page-handler="ResendOTP">Resend OTP</button> <br />

                           
                            
                            <div class="btn-style-3">
                                <button class="btn" asp-page-handler="RegisterAccount">Verify</button>
                            </div>

                        </form>
                        
                    </div>
                </div>
            </div>

        </div>
    </section>



    <!--== End Login Wrapper ==-->
</main>